# Generated by Django 5.0.7 on 2024-09-21 09:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('company_name', models.CharField(max_length=100)),
                ('street', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=100)),
                ('country', models.CharField(choices=[('DE', 'Germany')], max_length=2)),
                ('company_id', models.CharField(max_length=100)),
                ('hra_no', models.CharField(max_length=100)),
                ('hra_name', models.CharField(max_length=100)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=100)),
                ('contact_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='zip_code',
            new_name='postal_code',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line_1',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line_2',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address_line_3',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='email',
        ),
        migrations.AddField(
            model_name='customer',
            name='customer_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='street',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(choices=[('DE', 'Germany')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customer',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.project'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('due_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('buyer_reference', models.CharField(blank=True, max_length=100)),
                ('payment_means_code', models.CharField(choices=[('42', 'SEPA')], max_length=3)),
                ('payee_financial_account', models.CharField(max_length=100)),
                ('payment_terms', models.CharField(max_length=100)),
                ('tax_scheme', models.CharField(choices=[('VAT', 'VAT')], max_length=100)),
                ('price_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_net', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_full', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax_percentage', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.customer')),
                ('project', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.project')),
                ('invoice_positions', models.ManyToManyField(blank=True, to='invoicing.invoiceposition')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.supplier')),
            ],
        ),
    ]
