# Generated by Django 5.0.7 on 2024-09-21 13:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0003_rename_invoiceposition_invoiceitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoicing.project'),
        ),
    ]
