# Generated by Django 5.0.7 on 2024-09-21 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0004_supplier_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Supplier',
            new_name='Payee',
        ),
        migrations.RenameField(
            model_name='invoice',
            old_name='supplier',
            new_name='payee',
        ),
    ]
