# Generated by Django 5.0.7 on 2024-09-21 18:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0006_remove_invoice_invoice_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoice_items', to='invoicing.invoice'),
        ),
    ]
