# Generated by Django 5.0.7 on 2024-09-24 10:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0007_invoiceitem_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='contact_person',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='state',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_full',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_net',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='price_tax',
        ),
        migrations.RemoveField(
            model_name='payee',
            name='hra_name',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_means_code',
            field=models.CharField(choices=[('58', 'SEPA')], max_length=3),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='invoice',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_items', to='invoicing.invoice'),
        ),
    ]
