# Generated by Django 5.0.7 on 2024-09-24 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0009_invoice_checksum'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='checksum',
            new_name='hashed',
        ),
    ]
