# Generated by Django 5.0.7 on 2024-09-24 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0011_rename_hashed_invoice_snapshot_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='snapshot',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
